### ISSUE TITLE
Would it be in scope to have a function to tidy the user repos endpoint?

### ISSUE THREAD

**Issue by DaveParr** [rostools/githubr#13]
I've played around a little with the package, and I like it. I also understand that you have an objective in mind for it, and that not every endpoint is reasonable to have. How would you feel about a method to tidy the respons from `gh("GET /users/:username/repos", username = "daveparr")`?

A quick trial suggests it's not implemented currently:

```r
> githubr::tidy(gh("GET /users/:username/repos", username = "daveparr"))
Error in UseMethod("tidy", x) : 
  no applicable method for 'tidy' applied to an object of class "c('gh_response', 'list')"
```

If this isn't something that makes sense for you feel free to close :)

**Comment by lwjohnst86** [comment]
Hi @DaveParr thanks for the interest in the package! Yes, there's still lots I'd like to add to the package (if only I had more time), so this is definitely something that could be added too. I could try see about updating it in the next two weeks or so and ping you to try it out :)

**Comment by DaveParr** [comment]
If so that would be great, no huge rush though :)

**Comment by lwjohnst86** [comment]
Duh... this was a simple fix... I didn't export the S3 method! Oops.. I had already been planning on doing it with #7 but didn't realize this was related to it. Fixed :) Try it out now! Also, there is the package [tidyjson](https://github.com/colearendt/tidyjson) that can also tidy up JSON output like from GitHub, if you're interested in using something like that.

**Comment by DaveParr** [comment]
Thanks for the tip. In the end I actually did use tidyjson, and also hoist from purrr, to fix it up a bit and understand the return. thanks for working on this and also for the communication when it was done Ace job  🦾

**Comment by lwjohnst86** [comment]
No problem, happy you got it working :grin:
